### ISSUE TITLE
Faculty Feed not pulling through

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Asian-and-Middle-Eastern-Languages-and-Studies#1]
Hey WC the faculty feed isn't pulling through. All faculty are tagged accordingly and they all pull through on the CV in Drupal, but not to Jekyll. I have quadrupled checked the config files and for spelling errors.

**Comment by tu-chill** [comment]
No profiles have been tagged as Asian and Middle Eastern Languages and Studies.

**Comment by CVE82** [comment]
@tu-chill    I untagged them all because they were not pulling through and I didn't want any questions from faculty...
